name: Build and push Docker images

env:
  IMAGE_NAME: ohartl/dropbox-uploader

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - file: 'Dockerfile'
            platforms: 'linux/amd64,linux/386'
          - file: 'Dockerfile.arm32v6'
            platforms: 'linux/arm/v6'
          - file: 'Dockerfile.arm32v7'
            platforms: 'linux/arm/v7'
          - file: 'Dockerfile.arm64v8'
            platforms: 'linux/arm64'
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        #scan-ref: '.'
        ignore-unfixed: true
        format: 'template'
        #image-ref: '${{ steps.docker_meta.outputs.tags[0] }}'
        #'${{ env.IMAGE_NAME }}:'
        #format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'
    #- name: Upload Trivy scan results to GitHub Security tab
    #  uses: github/codeql-action/upload-sarif@v1
    #  with:
    #    sarif_file: 'trivy-results.sarif'
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ env.IMAGE_NAME }}
    #      ghcr.io/${{ env.IMAGE_NAME }}
        tag-latest: true
        tag-semver: |
          {{version}}
          {{major}}.{{minor}}
          {{major}}
        #tag-sha: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    #  with:
    #    driver-opts: network=host
    #- name: Build and push to local registry
    #  uses: docker/build-push-action@v2
    #  with:
    #    context: .
    #    push: true
    #    tags: localhost:5000/${{ env.IMAGE_NAME }}:latest
    #- name: Inspect
    #  run: |
    #    docker buildx imagetools inspect localhost:5000/${{ env.IMAGE_NAME }}:latest

    - name: Login to Docker Hub Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    #- name: Login to GitHub Container Registry
    #  if: github.event_name != 'pull_request'
    #  uses: docker/login-action@v1
    #  with:
    #    registry: ghcr.io
    #    username: ${{ github.repository_owner }}
    #    password: ${{ github.token }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: './${{ matrix.file }}'
        platforms: ${{ matrix.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

